=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/alberghi.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" xmlns="https://www.w3schools.com" elementFormDefault="qualified">

	<xsd:element name="alberghi">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="albergo" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="albergo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nome" type="xsd:string"/>
				<xsd:element name="citta" type="xsd:string"/>
				<xsd:element name="tel" type="xsd:string"/>
				<xsd:element name="cell" type="xsd:string" minOccurs="0"/>
				<xsd:element name="prezzo" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:integer">
								<xsd:attribute name="stanza" type="stanza"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="categoria" type="valutazione"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="valutazione">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="\*?\*?\*?\*?\*?"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="stanza">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="(singola|doppia)"/>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/alberghi.xml
<?xml version="1.0" encoding="UTF-8" ?>

<alberghi xmlns="https://www.alberghi.it" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="alberghi.xsd">
	<albergo categoria="****">
		<nome>Hotel Astoria</nome>
		<citta>Roma</citta>
		<tel>06237813</tel>
		<cell>353134125</cell>
		<prezzo stanza="singola">120</prezzo>
		<prezzo stanza="doppia">200</prezzo>
	</albergo>
	<albergo categoria="*">
		<nome>Pensione Scatafascio</nome>
		<citta>Roma</citta>
		<tel>068872382</tel>
		<prezzo stanza="doppia">50</prezzo>
		<prezzo stanza="singola">40</prezzo>
	</albergo>
</alberghi>
