=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/CartellaPosta.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mail.it" xmlns="http://mail.it" elementFormDefault="qualified">

	<xsd:element name="cartellaPosta">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="cartella" type="Tcartella" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="utente" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Tcartella">
		<xsd:sequence>
			<xsd:element name="messaggio" type="Tmessaggio" maxOccurs="unbounded" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="nome" type="Tnomecartella"/>
	</xsd:complexType>

	<xsd:simpleType name="Tnomecartella">
		<xsd:restriction base ="xsd:token">
			<xsd:pattern value="(Arrivata|Bozze)"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Tmessaggio">
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name="from" type="xsd:string"/>
				<xsd:element name="mittente" type="xsd:string"/>
			</xsd:choice>
			<xsd:choice>
				<xsd:element name="destinatari" type="xsd:string"/>
				<xsd:element name="to" type="xsd:string"/>
			</xsd:choice>
			<xsd:element name="ricevuto" type="xsd:string"/>
			<xsd:element name="oggetto" type="xsd:string"/>
			<xsd:element name="testo" type="Ttesto"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ttesto" mixed="true">
		<xsd:sequence>
			<xsd:element name="immagine" type="Timmagine" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Timmagine">
		<xsd:attribute name="src" type="xsd:string"/>
	</xsd:complexType>

</xsd:schema>

=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/CartellaPosta.xml
<?xml version="1.0" encoding="UTF-8"?>
<cartellaPosta utente="Quo"
	xmlns="http://mail.it"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="CartellaPosta.xsd" >
	<cartella nome="Arrivata">
		<messaggio>
			<mittente>Paperino</mittente>
			<destinatari>Qui, Quo, Qua</destinatari>
			<ricevuto>2016-06-17T12:30:00</ricevuto>
			<oggetto>Pranzo</oggetto>
			<testo>Vi aspetto per pranzo, dove siete?</testo>
		</messaggio>
		<messaggio>
			<mittente>Qua</mittente>
			<to>Qui, Quo</to>
			<ricevuto>2016-06-17T12:45:00</ricevuto>
			<oggetto>Re: Pranzo</oggetto>
			<testo>Ecco la foto dello zio arrabiato <immagine src="paperino.jpg" />
			</testo>
		</messaggio>
		<messaggio>
			<from>Qui</from>
			<destinatari>Quo, Qua</destinatari>
			<ricevuto>2016-06-17T12:40:00</ricevuto>
			<oggetto>Fw: Pranzo</oggetto>
			<testo>Siamo in ritardo per il pranzo! Lo zio ci gridera'!</testo>
		</messaggio>
	</cartella>
	<cartella nome="Bozze" />
</cartellaPosta>
