=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/film.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.film.com" targetNamespace="http://www.film.com" elementFormDefault="qualified">
	<xsd:element name="film">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="elementofilm" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="anno" type="xsd:positiveInteger"/>
							<xsd:element name="regista" type="xsd:string"/>
							<xsd:element name="attori">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="attore" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:string">
														<xsd:attribute name="personaggio" type="xsd:string" />
														<xsd:attribute name="ruolo" type="xsd:string" />
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="immagine" minOccurs="0" >
								<xsd:complexType>
									<xsd:attribute name="src" type="xsd:string" use="required"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>	
						<xsd:attribute name="titolo" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>	
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/film_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<film xmlns="http://www.film.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="film.xsd">
	<elementofilm titolo="Film123">
		<anno>1234</anno>
		<regista>Pinco Pallino</regista>
		<attori>
			<attore personaggio="Tizio" ruolo="Protagonista">
				Tizio
			</attore>
			<attore personaggio="Caio" ruolo="Secondario">
				Cesare
			</attore>
		</attori> 
		<immagine src="img123.jpg"/>
	</elementofilm>
	<elementofilm titolo="FilmAsd">
		<anno>2015</anno>
		<regista>Pinco Pallino</regista>
		<attori>
			<attore personaggio="Tizio">
				Tizio
			</attore>
			<attore>
				Cesare
			</attore>
		</attori>
	</elementofilm>
</film>
