=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/persone.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" xmlns="https://www.w3schools.com" elementFormDefault="qualified">
	<xsd:element name="persone">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="persona" type="Tpersona" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="personaConCodiceFiscale" type="TpersonaConCodiceFiscale" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Tpersona">
		<xsd:sequence>
			<xsd:element name="nome" type="xsd:string"/>
			<xsd:element name="sesso">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="M"/>
						<xsd:enumeration value="F"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="TpersonaConCodiceFiscale">
		<xsd:complexContent> <!-- NON TYPE! -->
			<xsd:extension base="Tpersona">
				<xsd:sequence>
					<xsd:element name="codFiscale" type="xsd:string"/>  
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/persone.xml
<?xml version="1.0" encoding="UTF-8"?>
<persone xmlns="https://www.w3schools.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="persone.xsd">
	<persona>
		<nome>Mirco</nome>
		<sesso>M</sesso>
	</persona>
	<persona>
		<nome>Marco</nome>
		<sesso>M</sesso>
	</persona>
	<personaConCodiceFiscale>
		<nome>Alessandro</nome>
		<sesso>M</sesso>
		<codFiscale>ASH43fhy83d64g7</codFiscale>
	</personaConCodiceFiscale>
</persone>
