=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/trasportoLibri.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" xmlns="https://www.w3schools.com" elementFormDefault="qualified">
	<xsd:element name="trasporti">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="trasporto" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="trasporto">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="seriale" type="xsd:long"/>
				<xsd:element ref="acquirente"/>
				<xsd:element ref="libro" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="acquirente">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nome" type="xsd:string"/>
				<xsd:element name="cognome" type="xsd:string"/>
				<xsd:element name="indirizzo" type="xsd:string"/>
				<xsd:element name="citta" type="xsd:string"/>
				<xsd:element name="cap" type="xsd:unsignedInt"/>
				<xsd:element name="nazione" type="xsd:string"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="libro">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ISBN13" type="ISBN13"/>
				<xsd:element name="titolo" type="xsd:string"/>
				<xsd:element name="note" type="xsd:string" minOccurs="0"/>
				<xsd:element name="quantita" type="xsd:unsignedInt"/>
				<xsd:element name="prezzo" type="xsd:decimal"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name ="ISBN13">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="[0-9]{13}"/>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== M9k/TecWeb-esercizi-DTD-e-XMLSchema/trasportoLibri.xml
<?xml version="1.0" encoding="UTF-8"?>
<trasporti xmlns="https://www.w3schools.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="trasportoLibri.xsd">
	<trasporto>
		<seriale>829375693285573</seriale>
		<acquirente>
			<nome>Pinco</nome>
			<cognome>Pallino</cognome>
			<indirizzo>Via Rossi 4</indirizzo>
			<citta>Venezia</citta>
			<cap>53012</cap>
			<nazione>Italy</nazione>
		</acquirente>
		<libro>
			<ISBN13>1234567890123</ISBN13>
			<titolo>Miglior libro di sempre</titolo>
			<note>Con pacco regalo</note>
			<quantita>1</quantita>
			<prezzo>12.53</prezzo>
		</libro>
	</trasporto>
	<trasporto>
		<seriale>829324342285573</seriale>
		<acquirente>
			<nome>Tizio</nome>
			<cognome>Caio</cognome>
			<indirizzo>Via Roma 123</indirizzo>
			<citta>Roma</citta>
			<cap>62034</cap>
			<nazione>Italy</nazione>
		</acquirente>
		<libro>
			<ISBN13>1234567890123</ISBN13>
			<titolo>Miglior libro di sempre</titolo>
			<quantita>10</quantita>
			<prezzo>109.99</prezzo>
		</libro>
		<libro>
			<ISBN13>1234567890123</ISBN13>
			<titolo>Libro a caso</titolo>
			<quantita>1</quantita>
			<prezzo>19.99</prezzo>
		</libro>
	</trasporto>
</trasporti>
